// <auto-generated />
using System;
using CodeBridgeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeBridgeApi.Migrations
{
    [DbContext(typeof(DogDbContext))]
    [Migration("20230602203445_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeBridgeApi.Models.Dog", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tail_Length")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Name = "Neo",
                            Color = "red & amber",
                            Tail_Length = 22,
                            Weight = 32
                        },
                        new
                        {
                            Name = "Jessy",
                            Color = "black & white",
                            Tail_Length = 7,
                            Weight = 14
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
